// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "9242f858-bd5d-49b7-8d91-4016416f9511";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


String altitud;
String humedad;
String magnetismo_x;
String magnetismo_y;
String magnetismo_z;
String nro_packet;
String presion_absoluta;
String presion_base;
String temperatura;
float altitud_chart;
float magnetismo_x_chart;
float magnetismo_y_chart;
float magnetismo_z_chart;
float presion_absoluta_chart;
float presion_base_chart;
float temperatura_chart;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(altitud, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humedad, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(magnetismo_x, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(magnetismo_y, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(magnetismo_z, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(nro_packet, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(presion_absoluta, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(presion_base, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperatura, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(altitud_chart, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(magnetismo_x_chart, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(magnetismo_y_chart, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(magnetismo_z_chart, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(presion_absoluta_chart, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(presion_base_chart, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperatura_chart, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
